import Navbar from '@/components/navbar/navbar'
import './globals.css'
import Footer from '@/components/footer/footer'
import { Providers } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <Navbar />
        {children}
        <Footer />
      </Providers>
      </body>
    </html>
  )
}
